<?php

use Drupal\xtended_entity_test\TestType;
use Drupal\xtended_entity_test\TestBuildingTerm;

function xtended_entity_test_node_info() {
  
  $types = array();  
  $types['test_type'] = array(
    'name' => 'Services and others', 
    'base' => 'xtended_entity_test', 
    'description' => t('destination content type'), 
    'locked' => TRUE
  );
  return $types;  
}

function xtended_entity_test_entity_info_alter( &$infos ) {
  $infos['node']['bundles']['test_type']['bundle class'] = TestType::class;  
  $infos['taxonomy_term']['bundles']['buildings']['bundle class'] = TestBuildingTerm::class;
}

function xtended_entity_test_insert( $node ) {
  
}

function xtended_entity_test_update( $node ) {
  
}

function xtended_entity_test_delete( $node ) {
  
}

